# Generated by Django 5.2.6 on 2025-12-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_procesamientoaudio_album_procesamientoaudio_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesamientoaudio',
            name='bpm',
        ),
    ]
